### ISSUE TITLE
Validation of data as part of beacon2-ri-tools-v2

### ISSUE THREAD

**Issue by solcos** [EGA-archive/beacon2-ri-tools-v2#24]
Validate the data transformed using beacon2-ri-tools-v2. The data in the CSVs/VCFs or/and the data in the BFF files. 

It's syntax, semantics, structure,...

Tell the user where and what failed in order to know what to change easily and respect the specifications.

**Comment by costero-e** [comment]
Validation (semantic and schema validation) has been added and now all files will be validated against specifications. This has been added in commit c1f2d9d6b11cb186cb0e0714ad754581dbcff2a2.
